[package]
name = "renderer"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
client = []
server = []

[dependencies]
server = { path = "../server", default-features = false }
shared = { path = "../shared", default-features = false }
lightyear.workspace = true
bevy-inspector-egui.workspace = true
leafwing-input-manager.workspace = true
avian3d.workspace = true
bevy = { workspace = true, features = [
    "bevy_asset",
    "bevy_render",
    "bevy_pbr",
    "bevy_scene",
    "bevy_core_pipeline",
    "bevy_gizmos",
    "tonemapping_luts",
    "smaa_luts",
    "default_font",
    "png",
    "hdr",
    "x11",
    "webgl2",
    "bevy_winit",
    "bevy_picking",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "bevy_window",
]}
bevy_config_stack.workspace = true
bevy_rich_text3d.workspace = true
serde.workspace = true
rand.workspace = true
sfx.workspace = true
vfx.workspace = true

[lints]
workspace = true
